// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopSampleWebApi.DataAccess;

#nullable disable

namespace ShopSampleWebApi.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241102085258_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopSampleWebApi.DataAccess.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(4943),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=26",
                            Name = "Incredible Concrete Fish",
                            Price = 29464.254324756768000m
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(4992),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=221",
                            Name = "Licensed Steel Mouse",
                            Price = 29161.619845995636000m
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5023),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=967",
                            Name = "Tasty Steel Cheese",
                            Price = 37637.425780276482000m
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5036),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=40",
                            Name = "Licensed Soft Hat",
                            Price = 46010.652231765171000m
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5047),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=667",
                            Name = "Awesome Steel Salad",
                            Price = 44675.17262416364000m
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5059),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=1",
                            Name = "Licensed Wooden Soap",
                            Price = 31884.138616247133000m
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5071),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=170",
                            Name = "Unbranded Plastic Pizza",
                            Price = 13828.7834856692000m
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5085),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=893",
                            Name = "Handmade Rubber Computer",
                            Price = 3892.4100434771668000m
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5115),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImgUri = "https://picsum.photos/g/200/200/?image=763",
                            Name = "Small Plastic Chicken",
                            Price = 42355.674426735193000m
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5128),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=982",
                            Name = "Gorgeous Soft Gloves",
                            Price = 12639.352091038798000m
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5145),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=1010",
                            Name = "Intelligent Soft Car",
                            Price = 25297.379556832207000m
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5155),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=24",
                            Name = "Handcrafted Concrete Bike",
                            Price = 33126.370423937286000m
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5167),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=211",
                            Name = "Fantastic Soft Tuna",
                            Price = 26917.610871297978000m
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5178),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=25",
                            Name = "Refined Concrete Sausages",
                            Price = 11259.71469342855000m
                        },
                        new
                        {
                            Id = 15L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5199),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=839",
                            Name = "Licensed Soft Cheese",
                            Price = 46272.355407414716000m
                        },
                        new
                        {
                            Id = 16L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5209),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUri = "https://picsum.photos/g/200/200/?image=220",
                            Name = "Tasty Rubber Car",
                            Price = 24167.763143693609000m
                        },
                        new
                        {
                            Id = 17L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5220),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=219",
                            Name = "Rustic Cotton Sausages",
                            Price = 25425.792467927305000m
                        },
                        new
                        {
                            Id = 18L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5231),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=3",
                            Name = "Ergonomic Frozen Shirt",
                            Price = 49760.541654092275000m
                        },
                        new
                        {
                            Id = 19L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5242),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImgUri = "https://picsum.photos/g/200/200/?image=776",
                            Name = "Sleek Granite Ball",
                            Price = 22839.919218927922000m
                        },
                        new
                        {
                            Id = 20L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5251),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=895",
                            Name = "Ergonomic Wooden Sausages",
                            Price = 15917.933379520388000m
                        },
                        new
                        {
                            Id = 21L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5262),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=1041",
                            Name = "Intelligent Soft Pants",
                            Price = 47414.912225151358000m
                        },
                        new
                        {
                            Id = 22L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5296),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=650",
                            Name = "Gorgeous Rubber Chips",
                            Price = 8311.753740879273000m
                        },
                        new
                        {
                            Id = 23L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5305),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=342",
                            Name = "Intelligent Frozen Salad",
                            Price = 33519.667683683733000m
                        },
                        new
                        {
                            Id = 24L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5318),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=297",
                            Name = "Intelligent Concrete Table",
                            Price = 3133.580020390476000m
                        },
                        new
                        {
                            Id = 25L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5327),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=29",
                            Name = "Unbranded Metal Car",
                            Price = 25147.565688032087000m
                        },
                        new
                        {
                            Id = 26L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5335),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=323",
                            Name = "Unbranded Steel Chicken",
                            Price = 9769.916802923633000m
                        },
                        new
                        {
                            Id = 27L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5343),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=739",
                            Name = "Tasty Plastic Chips",
                            Price = 34734.188733336126000m
                        },
                        new
                        {
                            Id = 28L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5378),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=401",
                            Name = "Practical Soft Bike",
                            Price = 24879.89977226007000m
                        },
                        new
                        {
                            Id = 29L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5389),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=983",
                            Name = "Fantastic Soft Soap",
                            Price = 40174.67050922516000m
                        },
                        new
                        {
                            Id = 30L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5399),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=124",
                            Name = "Handmade Rubber Bike",
                            Price = 35169.765940720382000m
                        },
                        new
                        {
                            Id = 31L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5408),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=245",
                            Name = "Handmade Soft Towels",
                            Price = 21772.370822215446000m
                        },
                        new
                        {
                            Id = 32L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5419),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=515",
                            Name = "Generic Fresh Chair",
                            Price = 44781.59730473116000m
                        },
                        new
                        {
                            Id = 33L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5427),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=602",
                            Name = "Gorgeous Granite Towels",
                            Price = 30799.010941572887000m
                        },
                        new
                        {
                            Id = 34L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5454),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=471",
                            Name = "Licensed Concrete Cheese",
                            Price = 34934.341076999902000m
                        },
                        new
                        {
                            Id = 35L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5464),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=588",
                            Name = "Awesome Frozen Shirt",
                            Price = 27737.593498983605000m
                        },
                        new
                        {
                            Id = 36L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5473),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=880",
                            Name = "Awesome Metal Chips",
                            Price = 28417.104913043531000m
                        },
                        new
                        {
                            Id = 37L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5482),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=144",
                            Name = "Handmade Cotton Chips",
                            Price = 4063.9886962798484000m
                        },
                        new
                        {
                            Id = 38L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5492),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=666",
                            Name = "Unbranded Cotton Soap",
                            Price = 20868.312940073192000m
                        },
                        new
                        {
                            Id = 39L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5500),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=275",
                            Name = "Intelligent Steel Bacon",
                            Price = 14650.365506905323000m
                        },
                        new
                        {
                            Id = 40L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5510),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=1003",
                            Name = "Intelligent Wooden Towels",
                            Price = 36156.383646821969000m
                        },
                        new
                        {
                            Id = 41L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5537),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=352",
                            Name = "Ergonomic Metal Ball",
                            Price = 30496.699700439818000m
                        },
                        new
                        {
                            Id = 42L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5546),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=619",
                            Name = "Incredible Frozen Shirt",
                            Price = 47118.486623777904000m
                        },
                        new
                        {
                            Id = 43L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5555),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=906",
                            Name = "Fantastic Metal Mouse",
                            Price = 42008.111219299406000m
                        },
                        new
                        {
                            Id = 44L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5564),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=473",
                            Name = "Small Granite Car",
                            Price = 27263.890773061249000m
                        },
                        new
                        {
                            Id = 45L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5574),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=434",
                            Name = "Awesome Granite Shoes",
                            Price = 21783.113089187246000m
                        },
                        new
                        {
                            Id = 46L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5583),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=143",
                            Name = "Awesome Steel Sausages",
                            Price = 42607.86029960315000m
                        },
                        new
                        {
                            Id = 47L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5610),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=633",
                            Name = "Ergonomic Frozen Shoes",
                            Price = 14812.253726681795000m
                        },
                        new
                        {
                            Id = 48L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5621),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUri = "https://picsum.photos/g/200/200/?image=8",
                            Name = "Unbranded Fresh Fish",
                            Price = 33940.870826801084000m
                        },
                        new
                        {
                            Id = 49L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5630),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=430",
                            Name = "Awesome Metal Soap",
                            Price = 23778.845881966237000m
                        },
                        new
                        {
                            Id = 50L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5639),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImgUri = "https://picsum.photos/g/200/200/?image=97",
                            Name = "Rustic Plastic Chicken",
                            Price = 18094.850542796012000m
                        },
                        new
                        {
                            Id = 51L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5647),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=256",
                            Name = "Refined Cotton Salad",
                            Price = 39968.807219844082000m
                        },
                        new
                        {
                            Id = 52L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5656),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=642",
                            Name = "Tasty Cotton Chips",
                            Price = 40645.641828280404000m
                        },
                        new
                        {
                            Id = 53L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5665),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=817",
                            Name = "Fantastic Concrete Tuna",
                            Price = 11842.437694650268000m
                        },
                        new
                        {
                            Id = 54L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5694),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUri = "https://picsum.photos/g/200/200/?image=593",
                            Name = "Practical Frozen Hat",
                            Price = 23959.991751156075000m
                        },
                        new
                        {
                            Id = 55L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5703),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=970",
                            Name = "Awesome Plastic Chicken",
                            Price = 39459.940709180501000m
                        },
                        new
                        {
                            Id = 56L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5712),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=243",
                            Name = "Handmade Concrete Shirt",
                            Price = 33641.267590695638000m
                        },
                        new
                        {
                            Id = 57L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5721),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=27",
                            Name = "Awesome Frozen Pizza",
                            Price = 11034.216904330136000m
                        },
                        new
                        {
                            Id = 58L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5730),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=977",
                            Name = "Ergonomic Fresh Pants",
                            Price = 40099.641742407617000m
                        },
                        new
                        {
                            Id = 59L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5739),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=535",
                            Name = "Licensed Concrete Salad",
                            Price = 44709.543442228412000m
                        },
                        new
                        {
                            Id = 60L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5747),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=796",
                            Name = "Licensed Fresh Chair",
                            Price = 23882.251782828347000m
                        },
                        new
                        {
                            Id = 61L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5775),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=317",
                            Name = "Refined Rubber Shoes",
                            Price = 48002.12750389674000m
                        },
                        new
                        {
                            Id = 62L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5784),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=300",
                            Name = "Licensed Metal Sausages",
                            Price = 42028.667345280776000m
                        },
                        new
                        {
                            Id = 63L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5794),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=634",
                            Name = "Unbranded Cotton Tuna",
                            Price = 33581.820170757291000m
                        },
                        new
                        {
                            Id = 64L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5803),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=115",
                            Name = "Refined Fresh Shirt",
                            Price = 21215.685312104961000m
                        },
                        new
                        {
                            Id = 65L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5812),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=958",
                            Name = "Refined Concrete Pizza",
                            Price = 25669.484742869638000m
                        },
                        new
                        {
                            Id = 66L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5822),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=475",
                            Name = "Refined Rubber Fish",
                            Price = 48727.376469724042000m
                        },
                        new
                        {
                            Id = 67L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5842),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=357",
                            Name = "Practical Cotton Soap",
                            Price = 20921.875522561803000m
                        },
                        new
                        {
                            Id = 68L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5851),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=150",
                            Name = "Unbranded Rubber Chips",
                            Price = 22182.76874723863000m
                        },
                        new
                        {
                            Id = 69L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5860),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=15",
                            Name = "Generic Concrete Chair",
                            Price = 30945.182399152622000m
                        },
                        new
                        {
                            Id = 70L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5869),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=800",
                            Name = "Fantastic Rubber Shoes",
                            Price = 7528.4361392285000m
                        },
                        new
                        {
                            Id = 71L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5877),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=708",
                            Name = "Unbranded Metal Tuna",
                            Price = 35095.459650670607000m
                        },
                        new
                        {
                            Id = 72L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5886),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=898",
                            Name = "Handmade Steel Towels",
                            Price = 28467.31019788035000m
                        },
                        new
                        {
                            Id = 73L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5917),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=793",
                            Name = "Awesome Plastic Towels",
                            Price = 38897.144260940174000m
                        },
                        new
                        {
                            Id = 74L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5926),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=562",
                            Name = "Intelligent Soft Soap",
                            Price = 47152.166615221058000m
                        },
                        new
                        {
                            Id = 75L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5935),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=285",
                            Name = "Awesome Frozen Salad",
                            Price = 34219.073193126863000m
                        },
                        new
                        {
                            Id = 76L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5944),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=589",
                            Name = "Rustic Rubber Shirt",
                            Price = 15715.575939942101000m
                        },
                        new
                        {
                            Id = 77L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5953),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=555",
                            Name = "Intelligent Soft Bike",
                            Price = 22427.757988555002000m
                        },
                        new
                        {
                            Id = 78L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5961),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=969",
                            Name = "Tasty Concrete Chair",
                            Price = 45387.770927361988000m
                        },
                        new
                        {
                            Id = 79L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(5970),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=160",
                            Name = "Handcrafted Fresh Chicken",
                            Price = 5062.1482734904848000m
                        },
                        new
                        {
                            Id = 80L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6005),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=442",
                            Name = "Sleek Cotton Fish",
                            Price = 34134.311340876018000m
                        },
                        new
                        {
                            Id = 81L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6015),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=845",
                            Name = "Licensed Granite Shoes",
                            Price = 12449.112580031007000m
                        },
                        new
                        {
                            Id = 82L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6024),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=384",
                            Name = "Rustic Granite Hat",
                            Price = 9506.621691832439000m
                        },
                        new
                        {
                            Id = 83L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6033),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImgUri = "https://picsum.photos/g/200/200/?image=920",
                            Name = "Practical Wooden Pizza",
                            Price = 49859.684851829411000m
                        },
                        new
                        {
                            Id = 84L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6042),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=853",
                            Name = "Refined Soft Salad",
                            Price = 12814.884173364839000m
                        },
                        new
                        {
                            Id = 85L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6050),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=125",
                            Name = "Handmade Wooden Computer",
                            Price = 30725.218910772784000m
                        },
                        new
                        {
                            Id = 86L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6077),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=469",
                            Name = "Refined Cotton Ball",
                            Price = 36398.985344451603000m
                        },
                        new
                        {
                            Id = 87L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6087),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=623",
                            Name = "Ergonomic Cotton Salad",
                            Price = 44246.951710848004000m
                        },
                        new
                        {
                            Id = 88L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6096),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=444",
                            Name = "Handcrafted Fresh Sausages",
                            Price = 14157.587309863731000m
                        },
                        new
                        {
                            Id = 89L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6104),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=101",
                            Name = "Handcrafted Metal Ball",
                            Price = 15719.657430565885000m
                        },
                        new
                        {
                            Id = 90L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6113),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=461",
                            Name = "Sleek Steel Keyboard",
                            Price = 3709.641043938234000m
                        },
                        new
                        {
                            Id = 91L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6122),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=1027",
                            Name = "Practical Steel Bike",
                            Price = 41138.398146069356000m
                        },
                        new
                        {
                            Id = 92L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6131),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUri = "https://picsum.photos/g/200/200/?image=235",
                            Name = "Licensed Cotton Towels",
                            Price = 19722.349643196451000m
                        },
                        new
                        {
                            Id = 93L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6159),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=68",
                            Name = "Ergonomic Steel Gloves",
                            Price = 25247.086666677469000m
                        },
                        new
                        {
                            Id = 94L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6168),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=447",
                            Name = "Generic Fresh Computer",
                            Price = 11381.064235252634000m
                        },
                        new
                        {
                            Id = 95L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6177),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=806",
                            Name = "Licensed Soft Car",
                            Price = 42465.17209688084000m
                        },
                        new
                        {
                            Id = 96L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6186),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=303",
                            Name = "Incredible Rubber Chair",
                            Price = 44692.458882355857000m
                        },
                        new
                        {
                            Id = 97L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6194),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=362",
                            Name = "Generic Wooden Shoes",
                            Price = 34291.612602509023000m
                        },
                        new
                        {
                            Id = 98L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6203),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=715",
                            Name = "Awesome Metal Computer",
                            Price = 22956.693061029643000m
                        },
                        new
                        {
                            Id = 99L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6212),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=312",
                            Name = "Ergonomic Frozen Towels",
                            Price = 48539.967336111418000m
                        },
                        new
                        {
                            Id = 100L,
                            CreatedOn = new DateTime(2024, 11, 2, 9, 52, 58, 169, DateTimeKind.Local).AddTicks(6239),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUri = "https://picsum.photos/g/200/200/?image=141",
                            Name = "Rustic Granite Bacon",
                            Price = 6296.216103771096000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
