// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopSampleWebApi.DataAccess;

#nullable disable

namespace ShopSampleWebApi.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241104082107_BaseEntityChanges")]
    partial class BaseEntityChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopSampleWebApi.DataAccess.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9048),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUri = "https://picsum.photos/g/200/200/?image=501",
                            Name = "Licensed Cotton Car",
                            Price = 10451.42124238375000m
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9102),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUri = "https://picsum.photos/g/200/200/?image=933",
                            Name = "Gorgeous Granite Chips",
                            Price = 36275.346760062017000m
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9123),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUri = "https://picsum.photos/g/200/200/?image=385",
                            Name = "Awesome Wooden Cheese",
                            Price = 17059.957289705301000m
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9142),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=957",
                            Name = "Awesome Steel Table",
                            Price = 10155.699797747881000m
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9166),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=821",
                            Name = "Ergonomic Rubber Shirt",
                            Price = 38155.599639847885000m
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9185),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=33",
                            Name = "Rustic Granite Keyboard",
                            Price = 17266.095235529594000m
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9204),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=70",
                            Name = "Awesome Steel Fish",
                            Price = 39338.369083738598000m
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9234),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=767",
                            Name = "Generic Cotton Chicken",
                            Price = 24846.580225735519000m
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9252),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=213",
                            Name = "Rustic Steel Sausages",
                            Price = 31888.621438490452000m
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9271),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=771",
                            Name = "Handcrafted Wooden Pants",
                            Price = 34770.661508831184000m
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9288),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=43",
                            Name = "Awesome Metal Fish",
                            Price = 28394.123887958814000m
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9310),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=1001",
                            Name = "Ergonomic Wooden Pants",
                            Price = 15011.434103718044000m
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9326),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=591",
                            Name = "Handmade Cotton Cheese",
                            Price = 9998.482666751606000m
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9368),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=632",
                            Name = "Ergonomic Frozen Table",
                            Price = 46200.185408754089000m
                        },
                        new
                        {
                            Id = 15L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9387),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=812",
                            Name = "Practical Frozen Fish",
                            Price = 32559.252182971352000m
                        },
                        new
                        {
                            Id = 16L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9403),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=186",
                            Name = "Handcrafted Wooden Bike",
                            Price = 15638.04783712607000m
                        },
                        new
                        {
                            Id = 17L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9421),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=621",
                            Name = "Small Steel Ball",
                            Price = 9380.318096273207000m
                        },
                        new
                        {
                            Id = 18L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9439),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=74",
                            Name = "Intelligent Cotton Table",
                            Price = 9340.274950108493000m
                        },
                        new
                        {
                            Id = 19L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9454),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=398",
                            Name = "Unbranded Rubber Shoes",
                            Price = 31416.528639597093000m
                        },
                        new
                        {
                            Id = 20L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9471),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=114",
                            Name = "Ergonomic Fresh Chicken",
                            Price = 15571.163485446099000m
                        },
                        new
                        {
                            Id = 21L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9512),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=785",
                            Name = "Generic Cotton Bacon",
                            Price = 47225.812012133138000m
                        },
                        new
                        {
                            Id = 22L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9530),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=712",
                            Name = "Handmade Rubber Mouse",
                            Price = 46271.361099747965000m
                        },
                        new
                        {
                            Id = 23L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9546),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=304",
                            Name = "Practical Granite Shoes",
                            Price = 4935.9063518868772000m
                        },
                        new
                        {
                            Id = 24L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9561),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=178",
                            Name = "Ergonomic Metal Chair",
                            Price = 28384.390795046005000m
                        },
                        new
                        {
                            Id = 25L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9576),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImgUri = "https://picsum.photos/g/200/200/?image=492",
                            Name = "Awesome Metal Hat",
                            Price = 35861.739477710957000m
                        },
                        new
                        {
                            Id = 26L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9594),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImgUri = "https://picsum.photos/g/200/200/?image=673",
                            Name = "Sleek Plastic Chips",
                            Price = 45318.607873751645000m
                        },
                        new
                        {
                            Id = 27L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9611),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=822",
                            Name = "Practical Rubber Table",
                            Price = 32967.189689986838000m
                        },
                        new
                        {
                            Id = 28L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9648),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=661",
                            Name = "Fantastic Soft Towels",
                            Price = 9668.989800693768000m
                        },
                        new
                        {
                            Id = 29L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9665),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=443",
                            Name = "Handcrafted Fresh Keyboard",
                            Price = 9681.850065529956000m
                        },
                        new
                        {
                            Id = 30L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9682),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=662",
                            Name = "Intelligent Concrete Tuna",
                            Price = 47997.881627290916000m
                        },
                        new
                        {
                            Id = 31L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9700),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=1000",
                            Name = "Tasty Frozen Shoes",
                            Price = 30007.055490124936000m
                        },
                        new
                        {
                            Id = 32L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9715),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=985",
                            Name = "Handmade Soft Ball",
                            Price = 48610.615652764395000m
                        },
                        new
                        {
                            Id = 33L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9732),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=584",
                            Name = "Small Granite Bike",
                            Price = 17521.71654824138000m
                        },
                        new
                        {
                            Id = 34L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9766),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=579",
                            Name = "Handmade Metal Pizza",
                            Price = 25785.492696259582000m
                        },
                        new
                        {
                            Id = 35L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9783),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=53",
                            Name = "Sleek Plastic Fish",
                            Price = 25518.30292260034000m
                        },
                        new
                        {
                            Id = 36L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9799),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=557",
                            Name = "Generic Rubber Cheese",
                            Price = 23392.251544519297000m
                        },
                        new
                        {
                            Id = 37L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9815),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=386",
                            Name = "Handmade Rubber Hat",
                            Price = 29944.89798448647000m
                        },
                        new
                        {
                            Id = 38L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9831),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=45",
                            Name = "Generic Rubber Towels",
                            Price = 43849.774498207236000m
                        },
                        new
                        {
                            Id = 39L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9847),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=220",
                            Name = "Tasty Granite Bacon",
                            Price = 35291.850089711956000m
                        },
                        new
                        {
                            Id = 40L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9862),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=889",
                            Name = "Licensed Concrete Chips",
                            Price = 40823.001289083782000m
                        },
                        new
                        {
                            Id = 41L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9898),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=382",
                            Name = "Small Wooden Chips",
                            Price = 9859.579888962089000m
                        },
                        new
                        {
                            Id = 42L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9914),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=805",
                            Name = "Rustic Metal Tuna",
                            Price = 28129.532134466979000m
                        },
                        new
                        {
                            Id = 43L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9931),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=34",
                            Name = "Refined Rubber Tuna",
                            Price = 13366.238956287986000m
                        },
                        new
                        {
                            Id = 44L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9947),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=997",
                            Name = "Handmade Soft Chair",
                            Price = 27120.493884537528000m
                        },
                        new
                        {
                            Id = 45L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9963),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=463",
                            Name = "Awesome Granite Cheese",
                            Price = 24294.152708390788000m
                        },
                        new
                        {
                            Id = 46L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 249, DateTimeKind.Local).AddTicks(9978),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImgUri = "https://picsum.photos/g/200/200/?image=841",
                            Name = "Intelligent Metal Shirt",
                            Price = 23603.55004845266000m
                        },
                        new
                        {
                            Id = 47L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(10),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=995",
                            Name = "Ergonomic Cotton Fish",
                            Price = 40568.433101673896000m
                        },
                        new
                        {
                            Id = 48L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(26),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=243",
                            Name = "Refined Fresh Hat",
                            Price = 35922.503246150037000m
                        },
                        new
                        {
                            Id = 49L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(42),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=923",
                            Name = "Tasty Rubber Car",
                            Price = 29514.339794643892000m
                        },
                        new
                        {
                            Id = 50L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(56),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUri = "https://picsum.photos/g/200/200/?image=75",
                            Name = "Generic Concrete Computer",
                            Price = 31389.315365189487000m
                        },
                        new
                        {
                            Id = 51L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(71),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=353",
                            Name = "Sleek Frozen Bike",
                            Price = 32567.129271655187000m
                        },
                        new
                        {
                            Id = 52L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(85),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUri = "https://picsum.photos/g/200/200/?image=678",
                            Name = "Tasty Plastic Car",
                            Price = 36835.096401037248000m
                        },
                        new
                        {
                            Id = 53L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(100),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=345",
                            Name = "Handmade Rubber Ball",
                            Price = 35896.221714500062000m
                        },
                        new
                        {
                            Id = 54L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(141),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=761",
                            Name = "Handcrafted Granite Car",
                            Price = 20636.076779131939000m
                        },
                        new
                        {
                            Id = 55L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(157),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=474",
                            Name = "Refined Plastic Hat",
                            Price = 37203.250074041358000m
                        },
                        new
                        {
                            Id = 56L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(172),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=423",
                            Name = "Tasty Steel Shoes",
                            Price = 35169.007062568357000m
                        },
                        new
                        {
                            Id = 57L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(188),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=121",
                            Name = "Gorgeous Metal Shoes",
                            Price = 47562.650662179134000m
                        },
                        new
                        {
                            Id = 58L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(202),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImgUri = "https://picsum.photos/g/200/200/?image=129",
                            Name = "Ergonomic Fresh Salad",
                            Price = 39633.543957559299000m
                        },
                        new
                        {
                            Id = 59L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(218),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=83",
                            Name = "Unbranded Concrete Towels",
                            Price = 2931.0115024285099000m
                        },
                        new
                        {
                            Id = 60L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(232),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=850",
                            Name = "Small Granite Fish",
                            Price = 3164.2125173018252000m
                        },
                        new
                        {
                            Id = 61L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(258),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=208",
                            Name = "Incredible Soft Ball",
                            Price = 15221.303632220209000m
                        },
                        new
                        {
                            Id = 62L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(275),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=70",
                            Name = "Awesome Fresh Tuna",
                            Price = 20921.72179607568000m
                        },
                        new
                        {
                            Id = 63L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(291),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=836",
                            Name = "Small Wooden Soap",
                            Price = 34651.509672784045000m
                        },
                        new
                        {
                            Id = 64L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(306),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=478",
                            Name = "Handcrafted Frozen Towels",
                            Price = 3166.6116586879065000m
                        },
                        new
                        {
                            Id = 65L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(322),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=1058",
                            Name = "Intelligent Frozen Soap",
                            Price = 15584.966694701137000m
                        },
                        new
                        {
                            Id = 66L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(337),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=265",
                            Name = "Ergonomic Fresh Shirt",
                            Price = 31542.908983262935000m
                        },
                        new
                        {
                            Id = 67L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(374),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=7",
                            Name = "Ergonomic Wooden Cheese",
                            Price = 45246.886019415674000m
                        },
                        new
                        {
                            Id = 68L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(389),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=556",
                            Name = "Incredible Rubber Pants",
                            Price = 48532.186585286382000m
                        },
                        new
                        {
                            Id = 69L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(405),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=683",
                            Name = "Awesome Metal Shoes",
                            Price = 21781.254013850197000m
                        },
                        new
                        {
                            Id = 70L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(421),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=78",
                            Name = "Gorgeous Steel Hat",
                            Price = 23472.762471036297000m
                        },
                        new
                        {
                            Id = 71L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(437),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImgUri = "https://picsum.photos/g/200/200/?image=896",
                            Name = "Tasty Rubber Sausages",
                            Price = 1132.85975822078218000m
                        },
                        new
                        {
                            Id = 72L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(452),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=251",
                            Name = "Small Plastic Chips",
                            Price = 47820.692354340744000m
                        },
                        new
                        {
                            Id = 73L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(466),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=408",
                            Name = "Small Steel Mouse",
                            Price = 42057.360431395756000m
                        },
                        new
                        {
                            Id = 74L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(505),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=592",
                            Name = "Sleek Wooden Fish",
                            Price = 32611.63755292767000m
                        },
                        new
                        {
                            Id = 75L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(521),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=666",
                            Name = "Awesome Frozen Fish",
                            Price = 38591.465918873636000m
                        },
                        new
                        {
                            Id = 76L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(538),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=1059",
                            Name = "Practical Fresh Chair",
                            Price = 25978.842639789339000m
                        },
                        new
                        {
                            Id = 77L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(553),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=319",
                            Name = "Refined Steel Salad",
                            Price = 15187.363744052296000m
                        },
                        new
                        {
                            Id = 78L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(567),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImgUri = "https://picsum.photos/g/200/200/?image=629",
                            Name = "Sleek Frozen Chair",
                            Price = 34902.893297584444000m
                        },
                        new
                        {
                            Id = 79L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(583),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=928",
                            Name = "Intelligent Frozen Soap",
                            Price = 21594.959461593342000m
                        },
                        new
                        {
                            Id = 80L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(617),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImgUri = "https://picsum.photos/g/200/200/?image=340",
                            Name = "Refined Metal Pants",
                            Price = 17598.260333623997000m
                        },
                        new
                        {
                            Id = 81L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(633),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=115",
                            Name = "Practical Cotton Towels",
                            Price = 46360.344893555181000m
                        },
                        new
                        {
                            Id = 82L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(649),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=21",
                            Name = "Small Wooden Sausages",
                            Price = 25456.87901778275000m
                        },
                        new
                        {
                            Id = 83L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(664),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=95",
                            Name = "Gorgeous Fresh Mouse",
                            Price = 9215.589538562182000m
                        },
                        new
                        {
                            Id = 84L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(679),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImgUri = "https://picsum.photos/g/200/200/?image=230",
                            Name = "Generic Plastic Mouse",
                            Price = 31698.803654127539000m
                        },
                        new
                        {
                            Id = 85L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(694),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=640",
                            Name = "Ergonomic Cotton Keyboard",
                            Price = 10520.217373388582000m
                        },
                        new
                        {
                            Id = 86L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(709),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImgUri = "https://picsum.photos/g/200/200/?image=620",
                            Name = "Ergonomic Fresh Bacon",
                            Price = 11183.12734368566000m
                        },
                        new
                        {
                            Id = 87L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(743),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=1068",
                            Name = "Licensed Soft Table",
                            Price = 24535.048885492116000m
                        },
                        new
                        {
                            Id = 88L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(758),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=947",
                            Name = "Fantastic Rubber Cheese",
                            Price = 38357.543659186275000m
                        },
                        new
                        {
                            Id = 89L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(774),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=484",
                            Name = "Fantastic Rubber Pizza",
                            Price = 12876.089888560016000m
                        },
                        new
                        {
                            Id = 90L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(790),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=817",
                            Name = "Fantastic Frozen Gloves",
                            Price = 20555.812573630375000m
                        },
                        new
                        {
                            Id = 91L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(806),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImgUri = "https://picsum.photos/g/200/200/?image=928",
                            Name = "Licensed Wooden Shoes",
                            Price = 44069.699269023091000m
                        },
                        new
                        {
                            Id = 92L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(822),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=88",
                            Name = "Fantastic Plastic Towels",
                            Price = 40619.469730150093000m
                        },
                        new
                        {
                            Id = 93L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(854),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImgUri = "https://picsum.photos/g/200/200/?image=1012",
                            Name = "Unbranded Soft Chips",
                            Price = 23752.126898423167000m
                        },
                        new
                        {
                            Id = 94L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(872),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=393",
                            Name = "Handcrafted Soft Mouse",
                            Price = 26843.259460030089000m
                        },
                        new
                        {
                            Id = 95L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(888),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImgUri = "https://picsum.photos/g/200/200/?image=687",
                            Name = "Generic Wooden Chips",
                            Price = 26145.904878313765000m
                        },
                        new
                        {
                            Id = 96L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(903),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImgUri = "https://picsum.photos/g/200/200/?image=262",
                            Name = "Handcrafted Metal Pants",
                            Price = 22332.61410010381000m
                        },
                        new
                        {
                            Id = 97L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(918),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImgUri = "https://picsum.photos/g/200/200/?image=723",
                            Name = "Refined Metal Pants",
                            Price = 5749.5671900939318000m
                        },
                        new
                        {
                            Id = 98L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(934),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImgUri = "https://picsum.photos/g/200/200/?image=504",
                            Name = "Unbranded Frozen Hat",
                            Price = 34830.546150658831000m
                        },
                        new
                        {
                            Id = 99L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(949),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImgUri = "https://picsum.photos/g/200/200/?image=284",
                            Name = "Generic Frozen Fish",
                            Price = 8824.939536107421000m
                        },
                        new
                        {
                            Id = 100L,
                            CreatedOn = new DateTime(2024, 11, 4, 9, 21, 7, 250, DateTimeKind.Local).AddTicks(981),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImgUri = "https://picsum.photos/g/200/200/?image=234",
                            Name = "Gorgeous Rubber Computer",
                            Price = 46438.1824161475000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
